name: gnome-mahjongg
version: git
summary: Match tiles and clear the board
description: |
  A solitaire version of the classic Eastern tile game. Tiles are stacked on
  the board at the start of the game. The goal is to remove all the tiles in
  as little time as possible. Select two matching tiles and they will disappear
  from the board, but you can only select a tile if there is an empty space to
  its left or right at the same level. Be careful: tiles that look alike
  may actually be slightly different.

  GNOME Mahjongg features a variety of starting layouts, some easy and some
  difficult. If you get stuck, you can ask for a hint, but this adds a large
  time penalty.  

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes

slots:
  # for GtkApplication registration
  gnome-mahjongg:
    interface: dbus
    bus: session
    name: org.gnome.Mahjongg

apps:
  gnome-mahjongg:
    command: desktop-launch gnome-mahjongg
    plugs:
      - desktop
      - desktop-legacy
      - gsettings
      - unity7
      - wayland
    desktop: usr/share/applications/org.gnome.Mahjongg.desktop

parts:
  desktop-gnome-platform:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters: ["FLAVOR=gtk3"]
    build-packages:
      - build-essential
      - libgtk-3-dev
    override-build: |
      snapcraftctl build
      mkdir -pv $SNAPCRAFT_PART_INSTALL/gnome-platform
  gnome-mahjongg:
    after: [desktop-gnome-platform]
    source: .
    source-type: git
    override-build: |
      sed -i.bak -e 's|=org.gnome.Mahjongg$|=${SNAP}/meta/gui/org.gnome.Mahjongg.svg|g' data/org.gnome.Mahjongg.desktop.in
      snapcraftctl build
      mkdir -p $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../src/data/icons/hicolor/scalable/org.gnome.Mahjongg.svg $SNAPCRAFT_PART_INSTALL/meta/gui/
      cp ../install/snap/gnome-mahjongg/current/usr/share/applications/org.gnome.Mahjongg.desktop $SNAPCRAFT_PART_INSTALL/meta/gui/
    plugin: meson
    meson-parameters: [--prefix=/snap/gnome-mahjongg/current/usr]
    organize:
      snap/gnome-mahjongg/current/usr: usr
    build-packages:
      - gettext
      - itstool
      - libglib2.0-dev
      - libgtk-3-dev
      - librsvg2-dev
      - valac
